apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: HypershiftDeployment
metadata:
  name: aws-sample
spec:
  infrastructure:
    cloudProvider:
      name: my-cloud-provider-secret
    configure: True
    platform:
      aws:
        region: us-west-1


