---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: HypershiftDeployment
metadata:
  name: manifestwork-status
  namespace: default #${hostClusterNamespace}
spec:
  hostingCluster: local-cluster
  hostingNamespace: default
  override: MANIFESTWORK
  infrastructure:
    cloudProvider:
      name: aws
    configure: True
    platform:
      aws:
        region: us-east-1