name: 'Validate HostedCluster & NodePool CRDs'

on:
  workflow_dispatch:
  schedule:
    - cron: '00 21 * * *'
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: false

jobs:
  validate-crds:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/stolostron/hypershift-deployment-controller'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # For verification
      - name: Compare CRDs (HostedCluster & NodePool)
        run: |
          make validate-crds
